// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkzsryuitebpnkelakrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrenNyeXVpdGVicG5rZWxha3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzk0ODQsImV4cCI6MjA1OTcxNTQ4NH0.70QitNU8mBKVOfqNdOFRvF6leL59H2drXsGwFzyB82I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);